// was 268
var lo_total = 77;
var title_1 = [
"001. What is Economics?",
"002. Theory and Models",
"003. Relative Prices",
"004. Optimization",
"005. Scarcity",
"006. Resources",
"007. Choices",
"008. A Model of Production",
"009. Production Possibilities",
"010. Comparative Advantage",
"011. Specialization",
"012. Gains from Trade",
"013. Entrepreneurship and...",
"014. Technological Advance",
"015. An Introduction to Market...",
"016. The Market Continuim",
"017. Voluntary Trade ...",
"018. Dynamic Nature of Markets",
"019. The Circular Flow Model",
"020. The Demand Curve",
"021. Diminishing Marginal...",
"022. Market Demand",
"023. Change in Demand",
"024. Determinants of...",
"025. Income Changes",
"026. Tastes and Preferences",
"027. Substitutes / Complements",
"028. The Supply Curve",
"029. Market Supply",
"030. Change in Supply",
"031. Determinants of Supply",
"032. Resources and Technology",
"033. Taxes and Subsidies",
"034. Sellers and Expectations",
"035. Demand Supply and",
"036. Change in Demand",
"037. Change in Supply",
"038. Complex Changes...",
"039. Disequilibria: Surpluses...",
"040. Consumer Surplus",
"041. Producer Surplus",
"042. Total Surplus",
"043. Distortions: Price Ceilings",
"044. Distortions: Price Floors",
"045. Deadweight Loss",
"046. Elasticity",
"047. Price Elasticity of Demand",
"048. Elastic Inelastic Unitary",
"049. Linear Demand and Elasticity",
"050. The Midpoint Formula",
"051. Elasticity and Total Revenue",
"052. Determinants of Elasticity: Demand",
"053. Determinants of Elasticity: Substitutes",
"054. Determinants of Elasticity: Necessities",
"055. Cross Price Elasticity",
"056. Income Elasticity",
"057. Price Elasticity of Supply",
"058. Elastic Inelastic Unitary: Supply",
"059. Elasticity of Supply: Inputs",
"060. Marginal Benefits and Marginal Costs",
"061. MB and MC in Equilibrium",
"062. Positive Externalities",
"063. Negative Externalities",
"064. Market Failure: Demand",
"065. Market Failure: Supply",
"066. Public Goods",
"067. Utility and Marginal Utility",
"068. Diminishing Marginal Utility",
"069. Choice Theory and Purposeful Behavior",
"070. Equal-margainal Principle",
"071. Utility Maximization",
"072. Utility Maximization: Indifference Curves",
"073. Utility Maximization: Budget Constraints",
"074. Utility Maximization: Maximum Utility",
"075. Explicit and Implicit Costs",
"076. Economic and Accounting Profits",
"077. Short Run: Total and Marginal Product",
"078. Short Run: Fixed and Variable Costs",
"079. Short Run: Average Costs",
"080. Short Run: Marginal Costs",
"081. Long Run: Cost Curves",
"082. Decreasing Constant Increasing Costs",
"083. Characteristics",
"084. Firm Demand and Markets",
"085. Operations in the Short Run",
"086. Short Run Losses",
"087. Short Run Supply",
"088. Long Run Assumptions",
"089. Long Run Equilibrium",
"090. Changing Costs",
"091. Efficiency in the Long Run",
"092. Characteristics",
"093. Marginal Revenue",
"094. Profit Maxmization",
"095. Monopolistic Misconceptions",
"096. Economic Efficiency",
"097. Price Discrimination: First Degree",
"098. Price Discrimination: Second Degree",
"099. Price Discrimination: Third Degree",
"100. Regulation",
"101. Characteristics",
"102. Firm Demand",
"103. Short Run Equilibrium",
"104. Long Run Equilibrium",
"105. Economic Efficiency",
"106. Characteristics",
"107. Game Theory",
"108. Cartels",
"109. Economic Efficiency",
"110. The Demand for Resources",
"111. Marginal Revenue Product",
"112. Marginal Resource Cost",
"113. Optimal Resource Utilization",
"114. Determinants of Resource Demand",
"115. Elasticity of Resource Demand",
"116. The Least Cost Rule",
"117. Profit Maximization",
"118. Wage Determination",
"119. Nominal vs Real Wages",
"120. Competitive Labor Markets",
"121. Monopsony and Wages",
"122. Unions and Employment",
"123. Unions and Wages",
"124. Bilateral Monopoly and Wages",
"125. Wage Differentials",
"126. Economic Rent",
"127. Interest and Loanable Funds",
"128. Interest: Market Dynamics",
"129. Economic Profit",
"130. Circular Flow Model: Govenrment",
"131. Expenditures and Revenue: Federal",
"132. Expenditures and Revenues: State",
"133. Expenditures and Revenues: Local",
"134. Taxes: Progressive Proportional ...",
"135. Taxes: Personal",
"136. Taxes: Payroll",
"137. Taxes: Property",
"138. Taxes: Corporate",
"139. Taxes: Sales",
"140. Taxes: Economic Efficiency",
"141. Budget Deficits",
"142. National Public Debt",
"143. The Laffer Curve",
"144. Choice Under Uncertainty",
"145. Moral Hazard",
"146. Adverse Selection",
"147. Rational Ignorance",
"148. Majority Voting and Efficiency",
"149. Principal-Agent Problem",
"150. Special Interest",
"151. Rent-Seeking",
"152. Gross Domestic Product",
"153. Expenditures Approach",
"154. Expenditures: Consumption and Government",
"155. Expenditures: Domestic Investment",
"156. Expenditures: Gross Domestic Inv.",
"157. Expenditures: Net Exports",
"158. Income Approach",
"159. Personal and Disposable Income",
"160. Real GDP",
"161. GDP Deflator",
"162. An Imperfect Measure",
"163. National Output and Income", 
"164. Economic Growth",
"165. Property Rights",
"166. Financial Institutions",
"167. Trade",
"168. Competitive Markets",
"169. Rules of the Game",
"170. Entrepreneurship and Innovation",
"171. Supply Demand and Efficiency",
"172. The Production Possibilities Frontier",
"173. The Business Cycle",
"174. The Unemployment Rate",
"175. Types of Unemployment",
"176. The Natural Rate of Unemployment",
"177. The Inflation Rate",
"178. The Consumer Price Index",
"179. The CPI: Measuring Inflation",
"180. Cost Push Demand Pull Inflation",
"181. Nominal and Real Income",
"182. Introduction",
"183. Consumption and Income",
"184. Savings and Income",
"185. The Marginal Propensity to Consume",
"186. Determinants of Consumption",
"187. Determinants of Consumption: Income",
"188. Determinants of Consumption: Expectations",
"189. Investment Demand",
"190. Determinants of Investment Demand",
"191. Determinants: Rental Cost of Capital",
"192. Determinants: Technology",
"193. Determinants: Capital Goods",
"194. The GDP Multiplier",
"195. Aggregate Expenditure Equilibrium",
"196. An Algebraic Approach",
"197. Equilibrium Dynamics",
"198. Recessionary Gaps",
"199. Inflationary Gaps",
"200. Real Output and Inflation",
"201. Aggregate Demand",
"202. Determinants of Aggregate Demand",
"203. Determinants: Consumption and Investment",
"204. Determinants: Government and Net Exports",
"205. Aggregate Supply",
"206. Determinants of Aggregate Supply",
"207. Determinants: Resource Prices",
"208. Determinants: Institutions",
"209. Aggregate Supply Long Short Run",
"210. Equilibrium Dynamics",
"211. Equilibrium: Recessions and Expansions",
"212. The Phillips Curve",
"213. Stagflation",
"214. Disinflation",
"215. Expansionary Policy",
"216. Contractionary Policy",
"217. Automatic Stabilizers",
"218. Limitations",
"219. Money",
"220. The Money Supply",
"221. The Federal Reserve: Structure",
"222. The Federal Reserve: Functions",
"223. Fractional Reserve Banking",
"224. The Money Multiplier",
"225. Increasing the Money Supply",
"226. Decreasing the Money Supply",
"227. Interest Rates: The Price of Money",
"228. The Fisher Equation",
"229. Interest Rates and Market Dynamics",
"230. Interest Rates and Aggregate Demand",
"231. Open Market Operations",
"232. The Reserve Ratio",
"233. The Discount Rate",
"234. Other Monetary Policies",
"235. The Federal Funds Rate",
"236. Expansionary Policy",
"237. Contractionary Policy",
"238. The Taylor Rule",
"239. Mainstream",
"240. Monetarists",
"241. Real Business Cycles",
"242. Coordination Failures",
"243. Self-Correction",
"244. International Trade",
"245. Comparative Advantage",
"246. Specialization",
"247. Terms of Trade and Gains",
"248. World Prices",
"249. The Small Country Model",
"250. Welfare Effects of Trade",
"251. Barriers to Trade",
"252. Barriers to Trade: Tariffs",
"253. Barriers to Trade: Quotas",
"254. Barriers to Trade: Voluntary Restrictions",
"255. Export Subsidies",
"256. Promoting Trade",
"257. The Balance of Payments",
"258. The Current Account",
"259. The Capital Account",
"260. The Financial Account",
"261. Deficits and Surpluses",
"262. Exchange Rates",
"263. Exchange Rate Markets",
"264. Determinants of Exchange Rates",
"265. Determinants: Tastes and Income",
"266. Determinants: Expected Returns",
"267. Flexible Exchange Rates",
"268. Fixed Exchange Rates",
"",
"",
"",
""];