//
// 11-15-2017
//
var practice_1 = [
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/circular_flow.xhtml",
"none.html",
"none.html",
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/consumer_optimum.html",
"Microeconomic_Theory_11_07_2017/practice_micro/producer_optimum.html",

"Microeconomic_Theory_11_07_2017/practice_micro/ppf_dual.html",
"Microeconomic_Theory_11_07_2017/practice_micro/practice_rp_mrt.html",
"Microeconomic_Theory_11_07_2017/practice_micro/ppf3.html",
"none.html",
"none.html",
"none.html",

"Microeconomic_Theory_11_07_2017/practice_micro/market_simulation_05_25_2016.html",
"Microeconomic_Theory_11_07_2017/practice_micro/market_1.html",
"Microeconomic_Theory_11_07_2017/practice_micro/market_2_demand.html",
"Microeconomic_Theory_11_07_2017/practice_micro/market_2_supply.html",
"Microeconomic_Theory_11_07_2017/practice_micro/market_2.html",

"Microeconomic_Theory_11_07_2017/practice_micro/midpoint_formula.xhtml",
"Microeconomic_Theory_11_07_2017/practice_micro/price_elasticity_revenue.xhtml",

"none.html",
"none.html",
"none.html",
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/consumer_optimum.html",
"Microeconomic_Theory_11_07_2017/practice_micro/price_decomposition.html",
"Microeconomic_Theory_11_07_2017/practice_micro/consumer_surplus.xhtml",
"none.html",
"none.html",
"none.html",

"Microeconomic_Theory_11_07_2017/practice_micro/dmp.html",
"Microeconomic_Theory_11_07_2017/practice_micro/production_productivity.html",
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/mt_shut_down_10_23_2014.html",
"Microeconomic_Theory_11_07_2017/practice_micro/short_run_optimum.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/produceroptimum.html",
"none.html",

"none.html",
"none.html",
"none.html",
"Microeconomic_Theory_11_07_2017/practice_micro/profitmax_10_21_2014.html",
"Microeconomic_Theory_11_07_2017/practice_micro/mt_profit_max_10_19_2014.html",
"none.html",
"none.html",

"Microeconomic_Theory_11_07_2017/practice_micro/perfect_competition_dual.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",

"none.html",
"none.html",
"none.html",
"none.html",

"Microeconomic_Theory_11_07_2017/practice_micro/cartesian_lines.html",
"none.html",
"none.html",

"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html",
"none.html"
];
